server:
  port: 8080
spring:
  application:
    name: mes-core
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.mesproject.*
    producer:
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mes_core
    username: mes
    password: mes
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
