server {
  listen 80;

  location /operator/ {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /operator/index.html;
  }

  location /kiosk/ {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /kiosk/index.html;
  }

  location /api/core/ {
    proxy_pass http://mes-core:8080/;
  }

  location /api/hub/ {
    proxy_pass http://integration-hub:8083/;
  }
}
